spring:
  application:
    name: rated-webapp

server:
  port: 80

info:
  component: This is Webapp for Rated Forum.
           
hystrix:
  streamEnabled: true
  enabled: true
  
archaius:
  dynamicPropertyFactory:
    registerConfigWithJMX: true
  
endpoints:
    restart:
      enabled: true

---
spring:
  profiles: development
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: http://gitlab-aws2.ratedcloud.net/get-it-done/config-repository.git
      discovery:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:8761/eureka/
  instance:
    hostname: ${myserver.hostname}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
   levels:
     org.springframework.boot.env.PropertySourcesLoader: TRACE
     org.springframework.web: DEBUG        
---
spring:
  profiles: docker
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: http://gitlab-aws2.ratedcloud.net/get-it-done/config-repository.git
      discovery:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:8761/eureka/
  instance:
    hostname: ${myserver.hostname}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
   levels:
     org.springframework.boot.env.PropertySourcesLoader: TRACE
     org.springframework.web: DEBUG  
---