spring:
  application:
    name: user-service
    
info:
  component: This is user service.

server:
  port: 8090
    
hystrix:
  streamEnabled: true
  enabled: true
  
archaius:
  dynamicPropertyFactory:
    registerConfigWithJMX: true
  
endpoints:
    restart:
      enabled: true

oauth:
  resourceId: user-service
  clientId: 4f7ec648a48b9d3fa239b497f7b6b4d8019697bd
  clientSecret: edfeba07ec1dd4ff45928ee715a8e1ecc149a060
        
---
spring:
  profiles: docker
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/${db.schema}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format-sql: true
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: http://gitlab-aws2.ratedcloud.net/get-it-done/config-repository.git
      discovery:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:8761/eureka/
  instance:
    hostname: ${myserver.hostname}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

oauth:
  tokenEndpoint: http://${oauth.hostname}:8080/oauth/check_token
  
logging:
   levels:
     org.springframework.boot.env.PropertySourcesLoader: TRACE
     org.springframework.web: DEBUG  
---

spring:
  profiles: development
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.hostname}:3306/${db.schema}?autoReconnect=true
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: http://gitlab-aws2.ratedcloud.net/get-it-done/config-repository.git
      discovery:
        enabled: true
    bus:
      amqp:
        exchange: rated-forum
        enabled: true
  rabbitmq:
    name: user-service
    host: 54.194.95.123
    port: 5672
    username: admin
    password: Rated1234
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:8761/eureka/
  instance:
    hostname: ${myserver.hostname}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

oauth:
  tokenEndpoint: http://${oauth.hostname}:8080/oauth/check_token
  
logging:
   levels:
     org.springframework.boot.env.PropertySourcesLoader: TRACE
     org.springframework.web: DEBUG  
---